apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: book-api
spec:
  selector:
    matchLabels:
      name: book-api
  template:
    metadata:
      labels:
        name: book-api
    spec:
      containers:
        - name: book-api
          image: evanraisul/book-api