apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-api
spec:
  selector:
    matchLabels:
      app: book-api
  replicas: 1
  template:
    metadata:
      labels:
        app: book-api
    spec:
      containers:
        - image: evanraisul/book-api
          name: book-api
          ports:
            - containerPort: 4444
              name: book-api
