apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: book-api
spec:
  selector:
    matchLabels:
      name: book-api
  replicas: 3
  template:
    metadata:
      labels:
        name: book-api
    spec:
      containers:
        - name: book-api
          image: evanraisul/book-api
          ports:
            - containerPort: 4444
